#####################################################
#                                                   #
#   Fisier de configurare pentru clientul SVXLink   #
#         rolink.network / www.439100.ro            #
#####################################################

[GLOBAL]
MODULE_PATH=/opt/rolink/lib/modules
LOGICS=SimplexLogic,ReflectorLogic
CFG_DIR=/opt/rolink/conf/svxlink.d
TIMESTAMP_FORMAT="%d-%m-%Y %H:%M:%S"
CARD_SAMPLE_RATE=48000
CARD_CHANNELS=1
LOCATION_INFO=LocationInfo
LINKS=HotLink

[HotLink]
CONNECT_LOGICS=SimplexLogic:55,ReflectorLogic
DEFAULT_ACTIVE=1
TIMEOUT=300

[SimplexLogic]
TYPE=Simplex
RX=RxLocal
TX=TxLocal
MODULES=ModuleParrot
CALLSIGN=USER
SHORT_IDENT_INTERVAL=30
LONG_IDENT_INTERVAL=60
DTMF_CTRL_PTY=/tmp/dtmf
EVENT_HANDLER=/opt/rolink/share/events.tcl
DEFAULT_LANG=fr_FR
TIME_FORMAT=24

# RGR_SOUND_DELAY= Nombre de millisecondes à attendre après la fermeture du squelch avant d’émettre le roger beep. Le bip peut être désactivé avec -1 
# ou en commentant la ligne. En général, il vaut mieux régler le délai avec SQL_HANGTIME et laisser ce paramètre à 0.
RGR_SOUND_DELAY=0

# RGR_SOUND_ALWAYS= Active ou désactive le bip « roger » de fin de transmission.
# 0 = désactiver, 1 = activer.
RGR_SOUND_ALWAYS=1
FX_GAIN_NORMAL=-1
FX_GAIN_LOW=-18
MUTE_RX_ON_TX=0
MUTE_TX_ON_RX=0
FAN_START=0

[ReflectorLogic]
TYPE=ReflectorV2
HOSTS=f62dmr.fr:5300
HOST_PORT=5300
#HOST_PRIO=100
#HOST_PRIO_INC=1
#HOST_WEIGHT=10
CALLSIGN="USER-RE"
AUTH_KEY="USER"
OPUS_ENC_BITRATE=20000
JITTER_BUFFER_DELAY=300
DEFAULT_TG=59
MONITOR_TGS=59,100
TG_SELECT_TIMEOUT=60
TMP_MONITOR_TIMEOUT=1800
ANNOUNCE_REMOTE_MIN_INTERVAL=3600
ANNOUNCE_CONNECTION_STATUS=1
EVENT_HANDLER=/opt/rolink/share/events.tcl
DEFAULT_LANG=fr_FR
NODE_INFO_FILE=/opt/rolink/conf/rolink.json
UDP_HEARTBEAT_INTERVAL=45
MUTE_FIRST_TX_LOC=0
MUTE_FIRST_TX_REM=0
RECONNECT_SECONDS=5

[Voter]
TYPE=Voter
RECEIVERS=RxLocal
VOTING_DELAY=75
COMMAND_PTY=/tmp/voter

[RxLocal]
TYPE=Local
AUDIO_DEV=alsa:plughw:0
AUDIO_CHANNEL=0
SQL_DET=VOX
SQL_START_DELAY=0
SQL_DELAY=0
SQL_HANGTIME=2000
#SQL_EXTENDED_HANGTIME=1000
#SQL_EXTENDED_HANGTIME_THRESH=15
#SQL_TIMEOUT=600
VOX_FILTER_DEPTH=20
VOX_THRESH=1000
#CTCSS_MODE=2
#CTCSS_FQ=136.5
#CTCSS_SNR_OFFSET=0
#CTCSS_OPEN_THRESH=15
#CTCSS_CLOSE_THRESH=9
#CTCSS_BPF_LOW=60
#CTCSS_BPF_HIGH=270
SERIAL_PORT=/dev/ttyS0
SERIAL_PIN=CTS
#SERIAL_SET_PINS=DTR!RTS
#EVDEV_DEVNAME=/dev/input/by-id/usb-SYNIC_SYNIC_Wireless_Audio-event-if03
#EVDEV_OPEN=1,163,1
#EVDEV_CLOSE=1,163,0
#GPIO_SQL_PIN=gpio30
#PTY_PATH=/tmp/rx1_sql
#HID_DEVICE=/dev/hidraw3
#HID_SQL_PIN=VOL_UP
#SIGLEV_DET=TONE
SIGLEV_SLOPE=1
SIGLEV_OFFSET=0
#SIGLEV_BOGUS_THRESH=120
#TONE_SIGLEV_MAP=100,84,60,50,37,32,28,23,19,8
SIGLEV_OPEN_THRESH=30
SIGLEV_CLOSE_THRESH=10
DEEMPHASIS=0
#SQL_TAIL_ELIM=300
PREAMP=4
PEAK_METER=1
DTMF_DEC_TYPE=INTERNAL
DTMF_MUTING=1
DTMF_HANGTIME=40
DTMF_SERIAL=/dev/ttyS0
#DTMF_PTY=/tmp/rx1_dtmf
#DTMF_MAX_FWD_TWIST=8
#DTMF_MAX_REV_TWIST=4
#1750_MUTING=1
#SEL5_DEC_TYPE=INTERNAL
#SEL5_TYPE=ZVEI1
#FQ=433475000
#MODULATION=FM
#WBRX=WbRx1

[TxLocal]
TYPE=Local
TX_ID=T
AUDIO_DEV=alsa:plughw:0
AUDIO_CHANNEL=0
LIMITER_THRESH=-4
#LIMITER_THRESH=0
PTT_TYPE=GPIO
PTT_PIN=gpio7
PTT_HANGTIME=100
TIMEOUT=240
TX_DELAY=300
PREEMPHASIS=1
#PREEMPHASIS=0
MASTER_GAIN=10

[LocationInfo]
APRS_SERVER_LIST=franceaprs.zapto.org:10151
LON_POSITION=0.13.23E
LAT_POSITION=48.01.38N
FREQUENCY=446.000
CALLSIGN=ER-USER
TX_POWER=1
ANTENNA_GAIN=0
ANTENNA_HEIGHT=1m
ANTENNA_DIR=-1
PATH=WIDE1-2
BEACON_INTERVAL=15
STATISTICS_INTERVAL=20
TONE=0
PTY_PATH=/tmp/svxaprs
COMMENT=Hotlink - f62dmr.fr
